### ISSUE TITLE
Missing alleles in PANDORA database can be retrieved from IMGT database

### ISSUE THREAD

**Issue by heleensev** [X-lab-3D/PANDORA#203] opened 2022-10-10 14:30 UTC
The PANDORA database can be improved by adding alleles present in the IMGT database.
Both for MHCI and MHCII can be found here:
`http://ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/fasta/`

**Comment by DarioMarzella** [comment] 2022-10-11 12:31
Thanks for the link, I have emailed the author and asked them what source we should use.
In the meantime, it seems like the missing alleles issue was actually caused by a sequence length interval too strict I set. Fixed in 542ede1 .

**Closed by DarioMarzella** 2022-10-11 12:31 UTC
